//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pages()
        {
            this.personpageranks = new HashSet<personpageranks>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public int SiteID { get; set; }
        public Nullable<System.DateTime> FoundDateTime { get; set; }
        public Nullable<System.DateTime> LastScanDate { get; set; }
    
        public virtual sites sites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personpageranks> personpageranks { get; set; }
    }
}
