-- MySQL Script generated by MySQL Workbench
-- 07/05/16 19:26:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema geekbrains
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geekbrains
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geekbrains` DEFAULT CHARACTER SET utf8 ;
USE `geekbrains` ;

-- -----------------------------------------------------
-- Table `geekbrains`.`Persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geekbrains`.`Persons` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` NVARCHAR(2048) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geekbrains`.`Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geekbrains`.`Keywords` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` NVARCHAR(2048) NULL,
  `PersonID` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FKPersonIDPersonsID_idx` (`PersonID` ASC),
  CONSTRAINT `FK_KeywordsPersonID_PersonsID`
    FOREIGN KEY (`PersonID`)
    REFERENCES `geekbrains`.`Persons` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geekbrains`.`Sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geekbrains`.`Sites` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` NVARCHAR(2048) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geekbrains`.`Pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geekbrains`.`Pages` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Url` NVARCHAR(2048) NULL,
  `SiteID` INT NULL,
  `FoundDateTime` DATETIME NULL,
  `LastScanDate` DATETIME NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_PagesSiteID_SitesID_idx` (`SiteID` ASC),
  CONSTRAINT `FK_PagesSiteID_SitesID`
    FOREIGN KEY (`SiteID`)
    REFERENCES `geekbrains`.`Sites` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geekbrains`.`PersonPageRanks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geekbrains`.`PersonPageRanks` (
  `PersonID` INT NOT NULL,
  `PageID` INT NOT NULL,
  `Rank` INT NULL,
  PRIMARY KEY (`PersonID`, `PageID`),
  INDEX `FK_PersonPageRanksPageID_PagesID_idx` (`PageID` ASC),
  CONSTRAINT `FK_PersonPageRanksPersonID_PersonsID`
    FOREIGN KEY (`PersonID`)
    REFERENCES `geekbrains`.`Persons` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PersonPageRanksPageID_PagesID`
    FOREIGN KEY (`PageID`)
    REFERENCES `geekbrains`.`Pages` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geekbrains`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geekbrains`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` NVARCHAR(2048) NULL,
  `Login` NVARCHAR(2048) NULL,
  `Password` NVARCHAR(2048) NULL,
  `IsAdmin` NVARCHAR(2048) BINARY NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
